"""Generate dbt-native test YAML from DQLens profile results."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml
from dqlens.models import ColumnProfile, DatabaseProfile, TableProfile


def generate_dbt_tests(
    profile: DatabaseProfile,
    baseline: DatabaseProfile | None = None,
    output_path: str = "models/_dqlens_tests.yml",
    min_severity: str = "LOW",
) -> str:
    """Generate a dbt schema.yml file with auto-generated tests.

    Args:
        profile: Current database profile from DQLens
        baseline: Previous profile for drift thresholds (optional)
        output_path: Where to write the YAML file
        min_severity: Minimum severity to include

    Returns:
        Path to the generated file
    """
    models = []

    for table in profile.tables:
        baseline_table = baseline.get_table(table.table_name) if baseline else None
        model_def = _generate_model_tests(table, baseline_table)
        if model_def:
            models.append(model_def)

    if not models:
        return ""

    output = {
        "version": 2,
        "models": models,
    }

    # Add header comment
    header = (
        f"# Auto-generated by dbt-dqlens. Review and commit to your repo.\n"
        f"# Generated at: {datetime.now(timezone.utc).isoformat()}\n"
        f"# Re-run: dqlens-dbt generate-tests\n\n"
    )

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)

    with open(path, "w") as f:
        f.write(header)
        yaml.dump(output, f, default_flow_style=False, sort_keys=False)

    return str(path)


def _generate_model_tests(
    table: TableProfile,
    baseline: TableProfile | None,
) -> dict[str, Any] | None:
    """Generate test definitions for a single model."""
    columns_with_tests = []

    for col in table.columns:
        baseline_col = baseline.get_column(col.name) if baseline else None
        tests = _generate_column_tests(col, baseline_col, table)
        if tests:
            columns_with_tests.append({
                "name": col.name,
                "tests": tests,
            })

    if not columns_with_tests:
        return None

    return {
        "name": table.table_name,
        "tags": ["dqlens"],
        "columns": columns_with_tests,
    }


def _generate_column_tests(
    col: ColumnProfile,
    baseline_col: ColumnProfile | None,
    table: TableProfile,
) -> list[dict[str, Any] | str]:
    """Generate test list for a single column."""
    tests: list[dict[str, Any] | str] = []

    # Primary key: unique + not_null
    if col.is_primary_key or (col.is_unique and col.null_count == 0):
        tests.append("unique")
        tests.append("not_null")
        return tests  # PK columns don't need other checks

    # Not null (if column was 100% non-null)
    if col.null_count == 0 and col.row_count > 0:
        tests.append("not_null")

    # Null drift (if we have a baseline with nulls)
    if baseline_col and baseline_col.null_pct > 0 and col.null_pct > 0:
        tests.append({
            "dqlens_no_null_drift": {
                "baseline_pct": baseline_col.null_pct,
                "threshold_multiplier": 3,
            }
        })

    # Empty strings (for text columns with empty strings)
    if col.empty_string_pct > 0:
        tests.append({
            "dqlens_no_empty_strings": {
                "max_pct": max(30, round(col.empty_string_pct * 2)),
            }
        })

    # Outliers (for numeric columns with percentiles)
    if col.p25 is not None and col.p75 is not None:
        iqr = col.p75 - col.p25
        if iqr > 0:
            lower = col.p25 - 1.5 * iqr
            upper = col.p75 + 1.5 * iqr
            tests.append({
                "dqlens_no_outliers": {
                    "lower_bound": round(lower, 2),
                    "upper_bound": round(upper, 2),
                }
            })

    # FK integrity (for foreign key columns)
    if col.is_foreign_key and col.fk_target_table and col.fk_target_column:
        tests.append({
            "dqlens_no_orphans": {
                "target_model": f"ref('{col.fk_target_table}')",
                "target_column": col.fk_target_column,
            }
        })

    # Accepted values (for low-cardinality columns)
    if (
        col.distinct_count > 0
        and col.distinct_count <= 20
        and not col.is_primary_key
        and not col.is_unique
        and col.distinct_pct < 5
        and col.most_common_values
    ):
        values = [str(v[0]) for v in col.most_common_values if v[0] is not None]
        if values:
            tests.append({
                "accepted_values": {
                    "values": values,
                }
            })

    return tests
