{{
    config(
        materialized='table',
        schema=var('dqlens', {}).get('dqlens_schema', 'dqlens'),
        tags=['dqlens']
    )
}}

{#
    DQLens findings materialized as a queryable table.
    Reads from the dqlens_raw_findings seed CSV generated by `dqlens-dbt profile`.

    To populate:
        1. Run `dqlens-dbt profile` (generates seeds/dqlens_raw_findings.csv)
        2. Run `dbt seed` (loads the CSV into your warehouse)
        3. Run `dbt run --select dqlens_findings` (materializes this model)

    Or just run `dbt build --select tag:dqlens` to do it all.
#}

select
    finding_id,
    table_name,
    column_name,
    severity,
    category,
    message,
    detail,
    current_value,
    baseline_value,
    cast(detected_at as timestamp) as detected_at
from {{ ref('dqlens_raw_findings') }}
{% if var('dqlens', {}).get('min_severity', 'LOW') == 'HIGH' %}
where severity = 'HIGH'
{% elif var('dqlens', {}).get('min_severity', 'LOW') == 'MEDIUM' %}
where severity in ('HIGH', 'MEDIUM')
{% endif %}
order by
    case severity
        when 'HIGH' then 1
        when 'MEDIUM' then 2
        when 'LOW' then 3
    end,
    table_name,
    column_name
